### ISSUE TITLE
cli: gen-fixtures shows incorrect library version

### ISSUE THREAD

**Issue by WebSpider** [skodaconnect/myskoda#432]
Ran across this while working on a report of some missing info in the fixtures:

The `gen-fixtures` command returns library version `0.0.0` when invoked with `uv run myskoda`:

`uv run myskoda --user me --password mypass gen-fixtures --vehicle all --name parked get all` shows

```yaml
description: null
generation_time: '2025-05-15T19:06:47.254969+00:00'
library_version: 0.0.0
name: parked
reports:
- endpoint: info
  error: null

```
